import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Navbar
    nav_home: 'Home',
    nav_insights: 'Insights',
    nav_privacy: 'Privacy',
    nav_contact: 'Contact',
    nav_app: 'Open App',

    // Hero
    hero_subtitle: 'Real-time safety intelligence for everyone. Navigate your city with confidence using community-powered data.',
    hero_signal1_label: 'Community-Powered',
    hero_signal1_tip: 'Safety data contributed and verified by thousands of real users in your city.',
    hero_signal2_label: 'Verified & Trusted',
    hero_signal2_tip: 'All reports are cross-referenced with official sources and community validation.',
    hero_signal3_label: 'Real-Time Alerts',
    hero_signal3_tip: 'Instant notifications about safety incidents in your area as they happen.',
    hero_signal4_label: 'Always Available',
    hero_signal4_tip: 'Access safety information 24/7, even in areas with limited connectivity.',
    hero_cta_title: 'Download SafeWays',
    hero_cta_subtitle: 'and stay safe today.',
    hero_app_store: 'App Store',
    hero_google_play: 'Google Play',
    hero_web_version: 'Web Version',
    hero_mobile_notice: 'Mobile app coming soon. Try our web version now.',
    hero_survey_btn: 'Take our Safety Survey',

    // Purpose
    purpose_label: 'Our Mission',
    purpose_heading: 'Safety is a right, not a privilege.',
    purpose_p1: 'SafeWays was built to give everyone — especially women and marginalized groups — the tools to navigate public spaces with confidence.',
    purpose_p2: 'By combining community intelligence with real-time data, we help people make informed decisions about their safety every day.',
    stat1_desc: 'of women worldwide have experienced harassment in public spaces.',
    stat2_desc: 'women in the EU have experienced physical and/or sexual violence since age 15.',
    stat3_desc: 'women in the EU experienced stalking since the age of 15.',
    stat4_desc: 'women who experience partner violence report it to the police.',
    purpose_cta_title: 'We believe technology can change this.',
    purpose_cta_p1: 'SafeWays empowers communities to map danger, share safety tips, and support each other — creating a safer world through collective action.',
    purpose_cta_p2: '"When women are safe in public spaces, everyone benefits."',

    // Features
    features_heading: 'Everything You Need to Stay Safe',
    features_subheading: 'Powerful tools designed to keep you informed and protected wherever you go.',
    feat1_title: 'Safety Mapping',
    feat1_desc: 'Interactive maps showing verified safe zones, danger areas, and community-reported incidents in real time.',
    feat2_title: 'Incident Reporting',
    feat2_desc: 'Quickly and anonymously report safety concerns to help protect your community and alert others.',
    feat3_title: 'Community Network',
    feat3_desc: 'Connect with trusted contacts and local safety networks to stay informed and supported.',
    feat4_title: 'Personal Safety Score',
    feat4_desc: 'AI-powered risk assessment for any location based on historical data and real-time reports.',
    feat5_title: 'SOS & Emergency',
    feat5_desc: 'One-tap emergency alerts that notify your trusted contacts and local authorities instantly.',
    feat6_title: 'Safety Analytics',
    feat6_desc: 'Detailed insights and trends to help you understand and improve safety in your neighborhood.',

    // Blog
    blog_heading: 'Insights & Stories',
    blog_empty: 'New articles coming soon.',
    blog_cta: 'Want to contribute or learn more?',
    blog_cta_link: 'Contact us',

    // Contact Section
    contact_success_title: "Message Sent!",
    contact_success_desc: "Thank you for reaching out. We'll get back to you soon.",
    contact_send_another: 'Send another message',
    contact_send: 'Send us a message',
    contact_name: 'Your Name',
    contact_email: 'Email Address',
    contact_subject: 'Subject',
    contact_subject_placeholder: 'How can we help?',
    contact_message: 'Message',
    contact_message_placeholder: 'Tell us more about your question or feedback...',
    contact_submit: 'Send Message',
    contact_portal: 'You can also reach us directly at',

    // Contact Page
    contact_page_title: 'Contact Us',
    contact_page_subtitle: "Have questions about SafeWays or want to learn more about our urban safety intelligence platform? We'd love to hear from you.",
    contact_page_response: 'We aim to respond within 5 working days.',

    // Insights Page
    insights_page_title: 'Insights & Stories',
    insights_page_subtitle: 'Learn from our community, discover safety tips, and stay informed.',

    // Footer
    footer_desc: 'Empowering communities with real-time safety intelligence. Navigate your world with confidence.',
    footer_links: 'Quick Links',
    footer_home: 'Home',
    footer_insights: 'Insights',
    footer_contact: 'Contact',
    footer_app: 'Open App',
    footer_terms: 'Terms of Service',
    footer_privacy: 'Privacy Policy',
    footer_copy: '© 2025 SafeWays. All rights reserved.',
    footer_verified: 'Privacy Verified',

    // Privacy Policy
    privacy_title: 'Privacy Policy',
    privacy_updated: 'Last updated: January 2025',
    privacy_intro1: 'At SafeWays, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, and safeguard your data when you use our platform.',
    privacy_intro2: 'By using SafeWays, you agree to the collection and use of information in accordance with this policy.',
    privacy_s1_title: '1. Information We Collect',
    privacy_s1_personal_title: 'Personal Information',
    privacy_s1_personal_intro: 'When you create an account or use our services, we may collect:',
    privacy_s1_li1: 'Name and email address',
    privacy_s1_li2: 'Profile information you choose to provide',
    privacy_s1_li3: 'Usage data and app interactions',
    privacy_s1_li4: 'Device information and identifiers',
    privacy_s1_personal_note: 'We collect only the minimum information necessary to provide our services.',
    privacy_s1_location_title: 'Location Data',
    privacy_s1_location_intro: 'SafeWays uses location data to provide safety information. We collect:',
    privacy_s1_loc_li1: 'Real-time location when the app is in use (with your permission)',
    privacy_s1_loc_li2: 'Location history for safety mapping features',
    privacy_s1_loc_li3: 'General area information for community safety reports',
    privacy_s1_loc_li4: 'Emergency location data when SOS features are activated',
    privacy_s1_location_note: 'You can control location permissions through your device settings at any time.',
    privacy_prototype_notice: 'Important: SafeWays is currently in prototype/beta stage. While we take privacy seriously, some data practices may evolve as the platform develops. We will notify users of any significant changes.',
    privacy_s2_title: '2. How We Use Your Information',
    privacy_s2_intro: 'We use collected information to:',
    privacy_s2_li1: 'Provide and improve our safety intelligence services',
    privacy_s2_li2: 'Generate community safety maps and reports',
    privacy_s2_li3: 'Send emergency alerts and safety notifications',
    privacy_s2_li4: 'Analyze safety trends and patterns (anonymized)',
    privacy_s2_li5: 'Communicate platform updates and safety information',
    privacy_s2_li6: 'Ensure platform security and prevent abuse',
    privacy_s2_li7: 'Comply with legal obligations',
    privacy_s3_title: '3. Data Sharing',
    privacy_s3_p1: 'We do not sell your personal data. We may share anonymized, aggregated safety data with local authorities, research institutions, and safety organizations to improve public safety outcomes.',
    privacy_s3_p2: 'Individual user data is never shared with third parties for commercial purposes.',
    privacy_s4_title: '4. Your Rights',
    privacy_s4_intro: 'You have the right to:',
    privacy_s4_li1: 'Access your personal data',
    privacy_s4_li2: 'Correct inaccurate information',
    privacy_s4_li3: 'Delete your account and associated data',
    privacy_s4_li4: 'Export your data in a portable format',
    privacy_s4_note: 'To exercise these rights, please contact us.',
    privacy_s5_title: '5. Contact Us',
    privacy_s5_intro: 'If you have any questions about this Privacy Policy or our data practices, please reach out to our team:',
    privacy_s5_link: 'Contact SafeWays Team',

    // Terms of Service
    terms_back: 'Back to Home',
    terms_title: 'Terms of Service',
    terms_updated: 'Last updated: January 2025',
    terms_s1_title: '1. Acceptance of Terms',
    terms_s1_p1: 'By accessing or using SafeWays, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform.',
    terms_s1_p2: 'SafeWays reserves the right to modify these terms at any time. We will notify users of significant changes via email or in-app notification.',
    terms_s2_title: '2. Use of Service',
    terms_s2_intro: 'You agree to use SafeWays responsibly and in accordance with these guidelines:',
    terms_s2_li1: 'Provide accurate information when submitting safety reports',
    terms_s2_li2: 'Do not submit false or misleading safety information',
    terms_s2_li3: 'Respect the privacy and safety of other community members',
    terms_s2_li4: 'Do not use the platform for harassment or harmful purposes',
    terms_s2_li5: 'Comply with all applicable laws and regulations',
    terms_s3_title: '3. Safety Information Disclaimer',
    terms_s3_notice_title: '⚠️ Important Safety Notice',
    terms_s3_notice_body: 'SafeWays provides community-sourced safety information for informational purposes only. In any emergency, always contact local emergency services (such as 112 or 999) immediately.',
    terms_s3_intro: 'SafeWays safety data:',
    terms_s3_li1: 'Is community-sourced and may not be 100% accurate or current',
    terms_s3_li2: 'Should not replace professional security advice or emergency services',
    terms_s3_li3: 'May vary in accuracy based on community engagement in your area',
    terms_s4_title: '4. Contact & Support',
    terms_s4_intro: 'For questions about these terms or our services:',
    terms_s4_link: 'Contact our team',
    terms_s4_response: 'We aim to respond to all inquiries within 5 working days.',
  },

  es: {
    // Navbar
    nav_home: 'Inicio',
    nav_insights: 'Artículos',
    nav_privacy: 'Privacidad',
    nav_contact: 'Contacto',
    nav_app: 'Abrir App',

    // Hero
    hero_subtitle: 'Inteligencia de seguridad en tiempo real para todos. Navega tu ciudad con confianza usando la información proporcionada por usuarios en tu ciudad.',
    hero_signal1_label: 'Impulsado por usuarios en tu ciudad',
    hero_signal1_tip: 'Datos de seguridad aportados y verificados por usuarios reales en tu ciudad.',
    hero_signal2_label: 'Verificado y confiable',
    hero_signal2_tip: 'Todos los informes se contrastan con fuentes oficiales y validación comunitaria.',
    hero_signal3_label: 'Alertas en tiempo real',
    hero_signal3_tip: 'Notificaciones instantáneas sobre incidentes de seguridad en tu área.',
    hero_signal4_label: 'Siempre disponible',
    hero_signal4_tip: 'Accede a información de seguridad 24/7, incluso en zonas con conectividad limitada.',
    hero_cta_title: 'Descarga SafeWays',
    hero_cta_subtitle: 'y mantente seguro hoy.',
    hero_app_store: 'App Store',
    hero_google_play: 'Google Play',
    hero_web_version: 'Versión Web',
    hero_mobile_notice: 'App móvil próximamente. Prueba nuestra versión web ahora.',
    hero_survey_btn: 'Participa en nuestra encuesta de seguridad',

    // Purpose
    purpose_label: 'Nuestra Misión',
    purpose_heading: 'La seguridad es un derecho, no un privilegio.',
    purpose_p1: 'SafeWays fue creado para dar a todos — especialmente mujeres y grupos marginados — las herramientas para navegar espacios públicos con confianza.',
    purpose_p2: 'Combinando inteligencia comunitaria con datos en tiempo real, ayudamos a las personas a tomar decisiones informadas sobre su seguridad cada día.',
    stat1_desc: 'de las mujeres en todo el mundo han experimentado acoso en espacios públicos.',
    stat2_desc: 'mujeres en la UE han experimentado violencia física y/o sexual desde los 15 años.',
    stat3_desc: 'mujeres en la UE experimentaron acoso desde los 15 años.',
    stat4_desc: 'mujeres que sufren violencia de pareja la denuncian a la policía.',
    purpose_cta_title: 'Creemos que la tecnología puede cambiar esto.',
    purpose_cta_p1: 'SafeWays capacita a las comunidades para mapear el peligro, compartir consejos de seguridad y apoyarse mutuamente.',
    purpose_cta_p2: '"Cuando las mujeres están seguras en espacios públicos, todos se benefician."',

    // Features
    features_heading: 'Todo lo que necesitas para estar seguro',
    features_subheading: 'Herramientas potentes diseñadas para mantenerte informado y protegido donde vayas.',
    feat1_title: 'Mapeo de seguridad',
    feat1_desc: 'Mapas interactivos que muestran zonas seguras verificadas, áreas de peligro e incidentes reportados por la comunidad.',
    feat2_title: 'Reporte de incidentes',
    feat2_desc: 'Reporta de forma rápida y anónima preocupaciones de seguridad para proteger a tu comunidad.',
    feat3_title: 'Red comunitaria',
    feat3_desc: 'Conéctate con contactos de confianza y redes locales de seguridad para mantenerte informado.',
    feat4_title: 'Puntuación de seguridad personal',
    feat4_desc: 'Evaluación de riesgo impulsada por IA para cualquier ubicación basada en datos históricos.',
    feat5_title: 'SOS y emergencias',
    feat5_desc: 'Alertas de emergencia con un toque que notifican a tus contactos de confianza y autoridades locales.',
    feat6_title: 'Análisis de seguridad',
    feat6_desc: 'Perspectivas y tendencias detalladas para entender y mejorar la seguridad en tu vecindario.',

    // Blog
    blog_heading: 'Artículos y Relatos',
    blog_empty: 'Nuevos artículos próximamente.',
    blog_cta: '¿Quieres contribuir o saber más?',
    blog_cta_link: 'Contáctanos',

    // Contact Section
    contact_success_title: '¡Mensaje enviado!',
    contact_success_desc: 'Gracias por escribirnos. Te responderemos pronto.',
    contact_send_another: 'Enviar otro mensaje',
    contact_send: 'Envíanos un mensaje',
    contact_name: 'Tu nombre',
    contact_email: 'Correo electrónico',
    contact_subject: 'Asunto',
    contact_subject_placeholder: '¿Cómo podemos ayudarte?',
    contact_message: 'Mensaje',
    contact_message_placeholder: 'Cuéntanos más sobre tu pregunta o comentario...',
    contact_submit: 'Enviar mensaje',
    contact_portal: 'También puedes contactarnos directamente en',

    // Contact Page
    contact_page_title: 'Contáctanos',
    contact_page_subtitle: '¿Tienes preguntas sobre SafeWays? Nos encantaría escucharte.',
    contact_page_response: 'Intentamos responder en 5 días hábiles.',

    // Insights Page
    insights_page_title: 'Artículos y Relatos',
    insights_page_subtitle: 'Aprende de nuestra comunidad, descubre consejos de seguridad y mantente informado.',

    // Footer
    footer_desc: 'Empoderando comunidades con inteligencia de seguridad en tiempo real.',
    footer_links: 'Enlaces rápidos',
    footer_home: 'Inicio',
    footer_insights: 'Artículos',
    footer_contact: 'Contacto',
    footer_app: 'Abrir App',
    footer_terms: 'Términos de servicio',
    footer_privacy: 'Política de privacidad',
    footer_copy: '© 2025 SafeWays. Todos los derechos reservados.',
    footer_verified: 'Privacidad verificada',

    // Privacy Policy
    privacy_title: 'Política de Privacidad',
    privacy_updated: 'Última actualización: enero de 2025',
    privacy_intro1: 'En SafeWays, estamos comprometidos a proteger tu privacidad y garantizar la seguridad de tu información personal.',
    privacy_intro2: 'Al usar SafeWays, aceptas la recopilación y el uso de información de acuerdo con esta política.',
    privacy_s1_title: '1. Información que recopilamos',
    privacy_s1_personal_title: 'Información personal',
    privacy_s1_personal_intro: 'Cuando creas una cuenta o usas nuestros servicios, podemos recopilar:',
    privacy_s1_li1: 'Nombre y dirección de correo electrónico',
    privacy_s1_li2: 'Información de perfil que elijas proporcionar',
    privacy_s1_li3: 'Datos de uso e interacciones en la app',
    privacy_s1_li4: 'Información del dispositivo e identificadores',
    privacy_s1_personal_note: 'Recopilamos solo la información mínima necesaria para proporcionar nuestros servicios.',
    privacy_s1_location_title: 'Datos de ubicación',
    privacy_s1_location_intro: 'SafeWays usa datos de ubicación para proporcionar información de seguridad. Recopilamos:',
    privacy_s1_loc_li1: 'Ubicación en tiempo real cuando la app está en uso (con tu permiso)',
    privacy_s1_loc_li2: 'Historial de ubicación para funciones de mapeo de seguridad',
    privacy_s1_loc_li3: 'Información de área general para informes de seguridad comunitaria',
    privacy_s1_loc_li4: 'Datos de ubicación de emergencia cuando se activan las funciones SOS',
    privacy_s1_location_note: 'Puedes controlar los permisos de ubicación a través de la configuración de tu dispositivo en cualquier momento.',
    privacy_prototype_notice: 'Importante: SafeWays está actualmente en fase prototipo/beta. Aunque tomamos la privacidad en serio, algunas prácticas de datos pueden evolucionar a medida que se desarrolle la plataforma.',
    privacy_s2_title: '2. Cómo usamos tu información',
    privacy_s2_intro: 'Usamos la información recopilada para:',
    privacy_s2_li1: 'Proporcionar y mejorar nuestros servicios de inteligencia de seguridad',
    privacy_s2_li2: 'Generar mapas e informes de seguridad comunitaria',
    privacy_s2_li3: 'Enviar alertas de emergencia y notificaciones de seguridad',
    privacy_s2_li4: 'Analizar tendencias y patrones de seguridad (anonimizados)',
    privacy_s2_li5: 'Comunicar actualizaciones de la plataforma',
    privacy_s2_li6: 'Garantizar la seguridad de la plataforma y prevenir abusos',
    privacy_s2_li7: 'Cumplir con las obligaciones legales',
    privacy_s3_title: '3. Compartir datos',
    privacy_s3_p1: 'No vendemos tus datos personales. Podemos compartir datos de seguridad anonimizados y agregados con autoridades locales e instituciones de investigación.',
    privacy_s3_p2: 'Los datos de usuarios individuales nunca se comparten con terceros con fines comerciales.',
    privacy_s4_title: '4. Tus derechos',
    privacy_s4_intro: 'Tienes derecho a:',
    privacy_s4_li1: 'Acceder a tus datos personales',
    privacy_s4_li2: 'Corregir información inexacta',
    privacy_s4_li3: 'Eliminar tu cuenta y los datos asociados',
    privacy_s4_li4: 'Exportar tus datos en un formato portable',
    privacy_s4_note: 'Para ejercer estos derechos, contáctanos.',
    privacy_s5_title: '5. Contáctanos',
    privacy_s5_intro: 'Si tienes preguntas sobre esta Política de Privacidad, comunícate con nuestro equipo:',
    privacy_s5_link: 'Contactar al equipo de SafeWays',

    // Terms of Service
    terms_back: 'Volver al inicio',
    terms_title: 'Términos de Servicio',
    terms_updated: 'Última actualización: enero de 2025',
    terms_s1_title: '1. Aceptación de los términos',
    terms_s1_p1: 'Al acceder o usar SafeWays, aceptas estar vinculado por estos Términos de Servicio.',
    terms_s1_p2: 'SafeWays se reserva el derecho de modificar estos términos en cualquier momento.',
    terms_s2_title: '2. Uso del servicio',
    terms_s2_intro: 'Aceptas usar SafeWays de manera responsable:',
    terms_s2_li1: 'Proporcionar información precisa al enviar informes de seguridad',
    terms_s2_li2: 'No enviar información de seguridad falsa o engañosa',
    terms_s2_li3: 'Respetar la privacidad y seguridad de otros miembros de la comunidad',
    terms_s2_li4: 'No usar la plataforma para acoso o propósitos dañinos',
    terms_s2_li5: 'Cumplir con todas las leyes y regulaciones aplicables',
    terms_s3_title: '3. Aviso legal sobre información de seguridad',
    terms_s3_notice_title: '⚠️ Aviso importante de seguridad',
    terms_s3_notice_body: 'SafeWays proporciona información de seguridad de origen comunitario solo con fines informativos. En cualquier emergencia, siempre contacta los servicios de emergencia locales (como el 112) de inmediato.',
    terms_s3_intro: 'Los datos de seguridad de SafeWays:',
    terms_s3_li1: 'Son de origen comunitario y pueden no ser 100% precisos o actuales',
    terms_s3_li2: 'No deben reemplazar el asesoramiento de seguridad profesional ni los servicios de emergencia',
    terms_s3_li3: 'Pueden variar en precisión según la participación de la comunidad en tu área',
    terms_s4_title: '4. Contacto y soporte',
    terms_s4_intro: 'Para preguntas sobre estos términos o nuestros servicios:',
    terms_s4_link: 'Contacta a nuestro equipo',
    terms_s4_response: 'Intentamos responder a todas las consultas en 5 días hábiles.',
  },

  pl: {
    // Navbar
    nav_home: 'Strona główna',
    nav_insights: 'Artykuły',
    nav_privacy: 'Prywatność',
    nav_contact: 'Kontakt',
    nav_app: 'Otwórz aplikację',

    // Hero
    hero_subtitle: 'Inteligencja bezpieczeństwa w czasie rzeczywistym dla każdego. Poruszaj się po mieście pewnie dzięki danym od społeczności.',
    hero_signal1_label: 'Zasilany przez społeczność',
    hero_signal1_tip: 'Dane o bezpieczeństwie dostarczane i weryfikowane przez tysiące prawdziwych użytkowników w Twoim mieście.',
    hero_signal2_label: 'Zweryfikowany i zaufany',
    hero_signal2_tip: 'Wszystkie zgłoszenia są porównywane z oficjalnymi źródłami i weryfikowane przez społeczność.',
    hero_signal3_label: 'Alerty w czasie rzeczywistym',
    hero_signal3_tip: 'Natychmiastowe powiadomienia o zdarzeniach bezpieczeństwa w Twojej okolicy.',
    hero_signal4_label: 'Zawsze dostępny',
    hero_signal4_tip: 'Dostęp do informacji o bezpieczeństwie 24/7, nawet w miejscach z ograniczonym zasięgiem.',
    hero_cta_title: 'Pobierz SafeWays',
    hero_cta_subtitle: 'i bądź bezpieczny już dziś.',
    hero_app_store: 'App Store',
    hero_google_play: 'Google Play',
    hero_web_version: 'Wersja web',
    hero_mobile_notice: 'Aplikacja mobilna już wkrótce. Wypróbuj teraz wersję webową.',
    hero_survey_btn: 'Weź udział w ankiecie bezpieczeństwa',

    // Purpose
    purpose_label: 'Nasza misja',
    purpose_heading: 'Bezpieczeństwo to prawo, nie przywilej.',
    purpose_p1: 'SafeWays zostało stworzone, aby dać każdemu — zwłaszcza kobietom i grupom marginalizowanym — narzędzia do poruszania się w przestrzeni publicznej z pewnością siebie.',
    purpose_p2: 'Łącząc inteligencję społecznościową z danymi w czasie rzeczywistym, pomagamy ludziom podejmować świadome decyzje dotyczące bezpieczeństwa każdego dnia.',
    stat1_desc: 'kobiet na całym świecie doświadczyło molestowania w przestrzeni publicznej.',
    stat2_desc: 'kobiet w UE doświadczyło przemocy fizycznej i/lub seksualnej od 15. roku życia.',
    stat3_desc: 'kobiet w UE doświadczyło stalkingu od 15. roku życia.',
    stat4_desc: 'kobiet doświadczających przemocy ze strony partnera zgłasza to policji.',
    purpose_cta_title: 'Wierzymy, że technologia może to zmienić.',
    purpose_cta_p1: 'SafeWays wspiera społeczności w mapowaniu zagrożeń, dzieleniu się wskazówkami dotyczącymi bezpieczeństwa i wzajemnym wspieraniu się.',
    purpose_cta_p2: '"Kiedy kobiety są bezpieczne w przestrzeni publicznej, wszyscy na tym korzystają."',

    // Features
    features_heading: 'Wszystko, czego potrzebujesz, aby być bezpiecznym',
    features_subheading: 'Zaawansowane narzędzia zaprojektowane, aby informować Cię i chronić gdziekolwiek jesteś.',
    feat1_title: 'Mapowanie bezpieczeństwa',
    feat1_desc: 'Interaktywne mapy pokazujące zweryfikowane bezpieczne strefy, niebezpieczne obszary i zgłoszenia społeczności w czasie rzeczywistym.',
    feat2_title: 'Zgłaszanie incydentów',
    feat2_desc: 'Szybko i anonimowo zgłaszaj obawy dotyczące bezpieczeństwa, aby chronić swoją społeczność.',
    feat3_title: 'Sieć społecznościowa',
    feat3_desc: 'Połącz się z zaufanymi kontaktami i lokalnymi sieciami bezpieczeństwa, aby być na bieżąco.',
    feat4_title: 'Osobisty wynik bezpieczeństwa',
    feat4_desc: 'Ocena ryzyka oparta na AI dla dowolnej lokalizacji na podstawie danych historycznych.',
    feat5_title: 'SOS i nagłe przypadki',
    feat5_desc: 'Alerty awaryjne jednym dotknięciem, które powiadamiają Twoje zaufane kontakty i lokalne służby.',
    feat6_title: 'Analityka bezpieczeństwa',
    feat6_desc: 'Szczegółowe informacje i trendy pomagające zrozumieć i poprawić bezpieczeństwo w Twojej okolicy.',

    // Blog
    blog_heading: 'Artykuły i Historie',
    blog_empty: 'Nowe artykuły już wkrótce.',
    blog_cta: 'Chcesz się zaangażować lub dowiedzieć się więcej?',
    blog_cta_link: 'Skontaktuj się z nami',

    // Contact Section
    contact_success_title: 'Wiadomość wysłana!',
    contact_success_desc: 'Dziękujemy za kontakt. Odpowiemy wkrótce.',
    contact_send_another: 'Wyślij kolejną wiadomość',
    contact_send: 'Wyślij nam wiadomość',
    contact_name: 'Twoje imię',
    contact_email: 'Adres e-mail',
    contact_subject: 'Temat',
    contact_subject_placeholder: 'W czym możemy pomóc?',
    contact_message: 'Wiadomość',
    contact_message_placeholder: 'Powiedz nam więcej o swoim pytaniu lub opinii...',
    contact_submit: 'Wyślij wiadomość',
    contact_portal: 'Możesz się z nami skontaktować bezpośrednio pod adresem',

    // Contact Page
    contact_page_title: 'Kontakt',
    contact_page_subtitle: 'Masz pytania dotyczące SafeWays? Chętnie Cię wysłuchamy.',
    contact_page_response: 'Staramy się odpowiadać w ciągu 5 dni roboczych.',

    // Insights Page
    insights_page_title: 'Artykuły i Historie',
    insights_page_subtitle: 'Ucz się od naszej społeczności, odkrywaj wskazówki dotyczące bezpieczeństwa i bądź na bieżąco.',

    // Footer
    footer_desc: 'Wzmacniamy społeczności inteligencją bezpieczeństwa w czasie rzeczywistym.',
    footer_links: 'Szybkie linki',
    footer_home: 'Strona główna',
    footer_insights: 'Artykuły',
    footer_contact: 'Kontakt',
    footer_app: 'Otwórz aplikację',
    footer_terms: 'Warunki korzystania',
    footer_privacy: 'Polityka prywatności',
    footer_copy: '© 2025 SafeWays. Wszelkie prawa zastrzeżone.',
    footer_verified: 'Prywatność zweryfikowana',

    // Privacy Policy
    privacy_title: 'Polityka Prywatności',
    privacy_updated: 'Ostatnia aktualizacja: styczeń 2025',
    privacy_intro1: 'W SafeWays jesteśmy zaangażowani w ochronę Twojej prywatności i bezpieczeństwo Twoich danych osobowych.',
    privacy_intro2: 'Korzystając z SafeWays, zgadzasz się na gromadzenie i wykorzystywanie informacji zgodnie z niniejszą polityką.',
    privacy_s1_title: '1. Informacje, które zbieramy',
    privacy_s1_personal_title: 'Dane osobowe',
    privacy_s1_personal_intro: 'Gdy tworzysz konto lub korzystasz z naszych usług, możemy zbierać:',
    privacy_s1_li1: 'Imię i adres e-mail',
    privacy_s1_li2: 'Informacje profilowe, które zdecydujesz się podać',
    privacy_s1_li3: 'Dane użytkowania i interakcje z aplikacją',
    privacy_s1_li4: 'Informacje o urządzeniu i identyfikatory',
    privacy_s1_personal_note: 'Zbieramy tylko minimalne informacje niezbędne do świadczenia naszych usług.',
    privacy_s1_location_title: 'Dane lokalizacji',
    privacy_s1_location_intro: 'SafeWays używa danych lokalizacji do dostarczania informacji o bezpieczeństwie. Zbieramy:',
    privacy_s1_loc_li1: 'Lokalizację w czasie rzeczywistym, gdy aplikacja jest używana (za Twoją zgodą)',
    privacy_s1_loc_li2: 'Historię lokalizacji dla funkcji mapowania bezpieczeństwa',
    privacy_s1_loc_li3: 'Ogólne informacje o obszarze dla raportów bezpieczeństwa społeczności',
    privacy_s1_loc_li4: 'Dane lokalizacji awaryjnej po aktywacji funkcji SOS',
    privacy_s1_location_note: 'Możesz kontrolować uprawnienia lokalizacji poprzez ustawienia urządzenia w dowolnym momencie.',
    privacy_prototype_notice: 'Ważne: SafeWays jest obecnie w fazie prototypu/beta. Chociaż traktujemy prywatność poważnie, niektóre praktyki dotyczące danych mogą ewoluować wraz z rozwojem platformy.',
    privacy_s2_title: '2. Jak wykorzystujemy Twoje informacje',
    privacy_s2_intro: 'Używamy zebranych informacji, aby:',
    privacy_s2_li1: 'Świadczyć i ulepszać nasze usługi inteligencji bezpieczeństwa',
    privacy_s2_li2: 'Generować mapy i raporty bezpieczeństwa społeczności',
    privacy_s2_li3: 'Wysyłać alerty awaryjne i powiadomienia o bezpieczeństwie',
    privacy_s2_li4: 'Analizować trendy i wzorce bezpieczeństwa (zanonimizowane)',
    privacy_s2_li5: 'Komunikować aktualizacje platformy',
    privacy_s2_li6: 'Zapewniać bezpieczeństwo platformy i zapobiegać nadużyciom',
    privacy_s2_li7: 'Przestrzegać obowiązków prawnych',
    privacy_s3_title: '3. Udostępnianie danych',
    privacy_s3_p1: 'Nie sprzedajemy Twoich danych osobowych. Możemy udostępniać zanonimizowane, zagregowane dane bezpieczeństwa lokalnym władzom i instytucjom badawczym.',
    privacy_s3_p2: 'Dane poszczególnych użytkowników nigdy nie są udostępniane stronom trzecim w celach komercyjnych.',
    privacy_s4_title: '4. Twoje prawa',
    privacy_s4_intro: 'Masz prawo do:',
    privacy_s4_li1: 'Dostępu do swoich danych osobowych',
    privacy_s4_li2: 'Poprawienia niedokładnych informacji',
    privacy_s4_li3: 'Usunięcia swojego konta i powiązanych danych',
    privacy_s4_li4: 'Eksportu danych w przenośnym formacie',
    privacy_s4_note: 'Aby skorzystać z tych praw, skontaktuj się z nami.',
    privacy_s5_title: '5. Kontakt',
    privacy_s5_intro: 'Jeśli masz pytania dotyczące niniejszej Polityki Prywatności, skontaktuj się z naszym zespołem:',
    privacy_s5_link: 'Skontaktuj się z zespołem SafeWays',

    // Terms of Service
    terms_back: 'Powrót do strony głównej',
    terms_title: 'Warunki Korzystania z Usługi',
    terms_updated: 'Ostatnia aktualizacja: styczeń 2025',
    terms_s1_title: '1. Akceptacja warunków',
    terms_s1_p1: 'Uzyskując dostęp do SafeWays lub korzystając z niego, zgadzasz się na przestrzeganie niniejszych Warunków Korzystania z Usługi.',
    terms_s1_p2: 'SafeWays zastrzega sobie prawo do modyfikacji tych warunków w dowolnym czasie.',
    terms_s2_title: '2. Korzystanie z usługi',
    terms_s2_intro: 'Zgadzasz się korzystać z SafeWays w sposób odpowiedzialny:',
    terms_s2_li1: 'Podawać dokładne informacje podczas przesyłania raportów bezpieczeństwa',
    terms_s2_li2: 'Nie przesyłać fałszywych lub wprowadzających w błąd informacji o bezpieczeństwie',
    terms_s2_li3: 'Szanować prywatność i bezpieczeństwo innych członków społeczności',
    terms_s2_li4: 'Nie używać platformy do nękania lub szkodliwych celów',
    terms_s2_li5: 'Przestrzegać wszystkich obowiązujących przepisów prawa',
    terms_s3_title: '3. Zastrzeżenie dotyczące informacji o bezpieczeństwie',
    terms_s3_notice_title: '⚠️ Ważne ostrzeżenie dotyczące bezpieczeństwa',
    terms_s3_notice_body: 'SafeWays dostarcza informacje o bezpieczeństwie pochodzące od społeczności wyłącznie w celach informacyjnych. W każdej sytuacji awaryjnej zawsze natychmiast kontaktuj się z lokalnymi służbami ratunkowymi (np. 112).',
    terms_s3_intro: 'Dane bezpieczeństwa SafeWays:',
    terms_s3_li1: 'Pochodzą od społeczności i mogą nie być w 100% dokładne lub aktualne',
    terms_s3_li2: 'Nie powinny zastępować profesjonalnych porad dotyczących bezpieczeństwa ani służb ratunkowych',
    terms_s3_li3: 'Mogą różnić się dokładnością w zależności od zaangażowania społeczności w Twojej okolicy',
    terms_s4_title: '4. Kontakt i wsparcie',
    terms_s4_intro: 'W przypadku pytań dotyczących tych warunków lub naszych usług:',
    terms_s4_link: 'Skontaktuj się z naszym zespołem',
    terms_s4_response: 'Staramy się odpowiadać na wszystkie zapytania w ciągu 5 dni roboczych.',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language]?.[key] ?? translations['en']?.[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}